# People {#people}

## Current Members

### Moin Syed, Ph.D. - Director

Moin Syed is a McKnight Endowed Presidential Professor of Psychology at the University of Minnesota, Twin Cities. His research focuses on identity and personality development among ethnically and culturally-diverse adolescents and emerging adults. Dr. Syed has conducted numerous workshops on methods, open science, preregistration, and theory development across the U.S. and Europe, and has edited multiple special issues of journals focusing on Registered Reports, a new publication format that prioritizes study conceptualization and design over findings in order to combat publication bias. He is currently the Editor of Infant and Child Development., is co-Editor (with Kate C. McLean) of the Oxford Handbook of Identity Development, the past Editor of Emerging Adulthood, the official journal of the Society for the Study of Emerging Adulthood, and is past President of the International Society for Research on Identity. Google Scholar | OSF  | Twitter  | Blog

### Dulce Wilkinson Westberg, Ph.D. - Post Doctoral Researcher

Dulce Wilkinson Westberg is a Post Doctoral Researcher at the University of Minnesota, Twin Cities. Her research program focuses on the nature and implications of structural-individual relations within and across various identity domains including race-ethnicity, gender, and social class. She is particularly interested in diversity of identity-related experiences and seeks to identify and disrupt structural inequalities through her research in ways that help bridge systematic inequalities. Broadly, her interests include culture, identity development, personality, diversity, and social justice. Google Scholar | Twitter

### Phuong Linh L. Nguyen - Doctoral Student 

Linh is an international student from Hanoi, Vietnam. Her research program broadly covers personality change and personality assessments. In particular, she is interested in within-person variability in personality using both traditional longitudinal methods and intensive longitudinal designs for momentary fluctuations. She has a secondary specialization in statistics and research methods and completed a concurrent M.S. degree in Statistics at the U. For her dissertation, she will investigate assortative mating patterns in romantic dyads using different levels of personality as well as both static and dynamic assessments of personality traits. Upon graduation, she aims to apply her dual training to pursue a career as a quantitative research scientist or data scientist in people analytics domain. Google Scholar | Twitter | Personal Webpage

### Edward Chou - Doctoral Student 

Edward is a generalist who has found refuge in the field of personality psychology. He is particularly interested in personality assessment. His current research interests include integrating assessments of the individual (e.g., narrative identity, psychotherapy, value fulfillment) with those that focus on between-person differences (e.g., the trait hierarchy and its maladaptive variants). Through his research and teaching, he aims to help people understand themselves better, so that they can live fulfilling lives that are appropriate for their unique combination of personality, identity, and life circumstances. Google Scholar | Twitter

### Rudy Perez - Doctoral Student 

### Affiliated Doctoral Students

Moin Syed also co-supervises doctoral students at other institutions, particularly at the University of Gothenburg, Sweden

David Sandberg, Department of Psychology, University of Gothenburg, Sweden

Tommy Reinholdsson, Department of Psychology, University of Gothenburg, Sweden

## Alumni

### Lab Alums

Ummul-Kiram Kathawalla, Ph.D. (2021)

Jillian Fish, Ph.D. (2020)

Sarah (Morrison-Cohen) Nelson, Ph.D. (2019) 

Alex Ajayi, Ph.D. (2018)

Lauren Mitchell, Ph.D. (2018)

Lovey (Walker) Peissig, Ph.D. (2016) 

Hasan Atak, Ph.D. (Post-Doc, 2015-16)

José Causadias, Ph.D. (2014)

Mary Joyce Juan, Ph.D. (2014)

Reiko Hirai, Ph.D. (2013)

### Affiliated Lab Alums

Shogo Hihara, Ph.D. 

Py Lv Eriksson, Ph.D. 

Adam Kim, Ph.D. 

Sheila Frankfurt, Ph.D. 

Johanna Carlsson, Ph.D. 

Fanny Gyberg, Ph.D. 

Ursula Moffitt, Ph.D. 

Alison Hu, Ph.D. 

Joyce Lee, Ph.D. 

Xiang Zhou, Ph.D. 

AnnaMarie Vu, Ph.D. 

Nazneen Bahrassa, Ph.D. 

Reid Reichwald, Ph.D. 

Oh Myo Kim, Ph.D. 
